# Generated by Django 3.1.7 on 2021-03-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountno', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('info', models.CharField(max_length=500)),
                ('credit', models.IntegerField()),
                ('debit', models.IntegerField()),
                ('balance', models.IntegerField()),
            ],
        ),
    ]
